const COLORS = {
  BACKGROUND_COLOR: '#283550',
  BORDER_COLOR: '#4F5B76',
  WHITE_COLOR: '#FFFFFF',
  PINK_COLOR: '#FD4C8A',
  HEADER_COLOR: '#F9F9F9',
  BLACK_COLOR: '#000000',
  BOTTOMLINE_COLOR: '#1D1D1E',
  GRAY_COLOR : '#EDEDED',
  BLUE_COLOR : '#328FE9',
  DARK_GRAY_COLOR : '#D6D6D6',
};

export default COLORS;
